### ISSUE TITLE
KL loss isn't decreasing 

### ISSUE THREAD

**Issue by Juns1105** [facebookresearch/improved_vrnn#4]
Hi,
Thanks for sharing the codes, very impressive work.
When I trained the model on the Push-BAIR dataset following your comment, I have observed that the KL loss kept increasing (but the qualitative result seems great). After a bunch of training iterations, it started to decrease slowly. Is this normal?

Thanks.

**Comment by lluiscastrejonsubira** [comment]
Hi,

Yes, this is normal VAE behavior. First the KL increases indicating that the model is using the latent variables to get good reconstructions and then there is a phase where the KL decreases indicating that the prior and the posterior distributions are being matched.
